// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend/api/visualization.proto

package go_client // import "github.com/kubeflow/pipelines/backend/api/go_client"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Visualization_Type int32

const (
	Visualization_ROC_CURVE        Visualization_Type = 0
	Visualization_CONFUSION_MATRIX Visualization_Type = 1
	Visualization_TFDV             Visualization_Type = 2
	Visualization_TFMA             Visualization_Type = 3
	Visualization_TABLE            Visualization_Type = 4
)

var Visualization_Type_name = map[int32]string{
	0: "ROC_CURVE",
	1: "CONFUSION_MATRIX",
	2: "TFDV",
	3: "TFMA",
	4: "TABLE",
}
var Visualization_Type_value = map[string]int32{
	"ROC_CURVE":        0,
	"CONFUSION_MATRIX": 1,
	"TFDV":             2,
	"TFMA":             3,
	"TABLE":            4,
}

func (x Visualization_Type) String() string {
	return proto.EnumName(Visualization_Type_name, int32(x))
}
func (Visualization_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_visualization_efc3400df142ffd9, []int{1, 0}
}

type CreateVisualizationRequest struct {
	Visualization        *Visualization `protobuf:"bytes,1,opt,name=visualization,proto3" json:"visualization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateVisualizationRequest) Reset()         { *m = CreateVisualizationRequest{} }
func (m *CreateVisualizationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVisualizationRequest) ProtoMessage()    {}
func (*CreateVisualizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_visualization_efc3400df142ffd9, []int{0}
}
func (m *CreateVisualizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVisualizationRequest.Unmarshal(m, b)
}
func (m *CreateVisualizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVisualizationRequest.Marshal(b, m, deterministic)
}
func (dst *CreateVisualizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVisualizationRequest.Merge(dst, src)
}
func (m *CreateVisualizationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVisualizationRequest.Size(m)
}
func (m *CreateVisualizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVisualizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVisualizationRequest proto.InternalMessageInfo

func (m *CreateVisualizationRequest) GetVisualization() *Visualization {
	if m != nil {
		return m.Visualization
	}
	return nil
}

type Visualization struct {
	Type                 Visualization_Type `protobuf:"varint,1,opt,name=type,proto3,enum=api.Visualization_Type" json:"type,omitempty"`
	InputPath            string             `protobuf:"bytes,2,opt,name=inputPath,proto3" json:"inputPath,omitempty"`
	Arguments            string             `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Html                 string             `protobuf:"bytes,4,opt,name=html,proto3" json:"html,omitempty"`
	Error                string             `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Visualization) Reset()         { *m = Visualization{} }
func (m *Visualization) String() string { return proto.CompactTextString(m) }
func (*Visualization) ProtoMessage()    {}
func (*Visualization) Descriptor() ([]byte, []int) {
	return fileDescriptor_visualization_efc3400df142ffd9, []int{1}
}
func (m *Visualization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Visualization.Unmarshal(m, b)
}
func (m *Visualization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Visualization.Marshal(b, m, deterministic)
}
func (dst *Visualization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Visualization.Merge(dst, src)
}
func (m *Visualization) XXX_Size() int {
	return xxx_messageInfo_Visualization.Size(m)
}
func (m *Visualization) XXX_DiscardUnknown() {
	xxx_messageInfo_Visualization.DiscardUnknown(m)
}

var xxx_messageInfo_Visualization proto.InternalMessageInfo

func (m *Visualization) GetType() Visualization_Type {
	if m != nil {
		return m.Type
	}
	return Visualization_ROC_CURVE
}

func (m *Visualization) GetInputPath() string {
	if m != nil {
		return m.InputPath
	}
	return ""
}

func (m *Visualization) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *Visualization) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

func (m *Visualization) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateVisualizationRequest)(nil), "api.CreateVisualizationRequest")
	proto.RegisterType((*Visualization)(nil), "api.Visualization")
	proto.RegisterEnum("api.Visualization_Type", Visualization_Type_name, Visualization_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VisualizationServiceClient is the client API for VisualizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VisualizationServiceClient interface {
	CreateVisualization(ctx context.Context, in *CreateVisualizationRequest, opts ...grpc.CallOption) (*Visualization, error)
}

type visualizationServiceClient struct {
	cc *grpc.ClientConn
}

func NewVisualizationServiceClient(cc *grpc.ClientConn) VisualizationServiceClient {
	return &visualizationServiceClient{cc}
}

func (c *visualizationServiceClient) CreateVisualization(ctx context.Context, in *CreateVisualizationRequest, opts ...grpc.CallOption) (*Visualization, error) {
	out := new(Visualization)
	err := c.cc.Invoke(ctx, "/api.VisualizationService/CreateVisualization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisualizationServiceServer is the server API for VisualizationService service.
type VisualizationServiceServer interface {
	CreateVisualization(context.Context, *CreateVisualizationRequest) (*Visualization, error)
}

func RegisterVisualizationServiceServer(s *grpc.Server, srv VisualizationServiceServer) {
	s.RegisterService(&_VisualizationService_serviceDesc, srv)
}

func _VisualizationService_CreateVisualization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVisualizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualizationServiceServer).CreateVisualization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.VisualizationService/CreateVisualization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualizationServiceServer).CreateVisualization(ctx, req.(*CreateVisualizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VisualizationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.VisualizationService",
	HandlerType: (*VisualizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVisualization",
			Handler:    _VisualizationService_CreateVisualization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/api/visualization.proto",
}

func init() {
	proto.RegisterFile("backend/api/visualization.proto", fileDescriptor_visualization_efc3400df142ffd9)
}

var fileDescriptor_visualization_efc3400df142ffd9 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x13, 0xa7, 0x34, 0x53, 0x02, 0x66, 0x1b, 0xa9, 0x96, 0x15, 0x94, 0xc8, 0xa7, 0x4a,
	0x10, 0x5b, 0x4d, 0x2e, 0x88, 0x5b, 0x12, 0x5a, 0xa9, 0x88, 0x34, 0xc8, 0x49, 0x23, 0xd4, 0x4b,
	0xb4, 0x76, 0xa7, 0xce, 0xaa, 0x8e, 0x77, 0x59, 0xaf, 0x53, 0x95, 0x0b, 0x12, 0x12, 0x3f, 0x00,
	0x07, 0x3e, 0x8c, 0x5f, 0xe0, 0xcc, 0x37, 0xa0, 0x6c, 0xaa, 0x12, 0xab, 0xed, 0x69, 0x67, 0xe7,
	0xbd, 0x79, 0x3b, 0xfb, 0x66, 0xa0, 0x19, 0xd2, 0xe8, 0x0a, 0xd3, 0x0b, 0x9f, 0x0a, 0xe6, 0x2f,
	0x59, 0x96, 0xd3, 0x84, 0x7d, 0xa1, 0x8a, 0xf1, 0xd4, 0x13, 0x92, 0x2b, 0x4e, 0xca, 0x54, 0x30,
	0xa7, 0x11, 0x73, 0x1e, 0x27, 0xa8, 0x49, 0x34, 0x4d, 0xb9, 0xd2, 0x8c, 0x6c, 0x4d, 0x71, 0xf6,
	0x37, 0x35, 0x50, 0x4a, 0x2e, 0x6f, 0x81, 0xd7, 0xfa, 0x88, 0xda, 0x31, 0xa6, 0xed, 0xec, 0x9a,
	0xc6, 0x31, 0x4a, 0x9f, 0x0b, 0x5d, 0x7a, 0x5f, 0xc6, 0x9d, 0x82, 0x33, 0x90, 0x48, 0x15, 0x4e,
	0x37, 0xdb, 0x08, 0xf0, 0x73, 0x8e, 0x99, 0x22, 0x6f, 0xa0, 0x56, 0x68, 0xcf, 0x36, 0x5a, 0xc6,
	0xc1, 0x6e, 0x87, 0x78, 0x54, 0x30, 0xaf, 0x58, 0x51, 0x24, 0xba, 0x7f, 0x0d, 0xa8, 0x15, 0x08,
	0xe4, 0x15, 0x98, 0xea, 0x46, 0xa0, 0x96, 0x78, 0xd6, 0xd9, 0xbf, 0x2f, 0xe1, 0x4d, 0x6e, 0x04,
	0x06, 0x9a, 0x44, 0x1a, 0x50, 0x65, 0xa9, 0xc8, 0xd5, 0x47, 0xaa, 0xe6, 0x76, 0xa9, 0x65, 0x1c,
	0x54, 0x83, 0xff, 0x89, 0x15, 0x4a, 0x65, 0x9c, 0x2f, 0x30, 0x55, 0x99, 0x5d, 0x5e, 0xa3, 0x77,
	0x09, 0x42, 0xc0, 0x9c, 0xab, 0x45, 0x62, 0x9b, 0x1a, 0xd0, 0x31, 0xa9, 0x43, 0x45, 0x7b, 0x64,
	0x57, 0x74, 0x72, 0x7d, 0x71, 0xdf, 0x83, 0xb9, 0x7a, 0x93, 0xd4, 0xa0, 0x1a, 0x8c, 0x06, 0xb3,
	0xc1, 0x59, 0x30, 0x3d, 0xb2, 0xb6, 0x48, 0x1d, 0xac, 0xc1, 0xe8, 0xf4, 0xf8, 0x6c, 0x7c, 0x32,
	0x3a, 0x9d, 0x0d, 0x7b, 0x93, 0xe0, 0xe4, 0x93, 0x65, 0x90, 0x1d, 0x30, 0x27, 0xc7, 0xef, 0xa6,
	0x56, 0x69, 0x1d, 0x0d, 0x7b, 0x56, 0x99, 0x54, 0xa1, 0x32, 0xe9, 0xf5, 0x3f, 0x1c, 0x59, 0x66,
	0xe7, 0x97, 0x01, 0xf5, 0xc2, 0x77, 0xc6, 0x28, 0x97, 0x2c, 0x42, 0xf2, 0x15, 0xf6, 0x1e, 0x70,
	0x98, 0x34, 0xb5, 0x01, 0x8f, 0x7b, 0xef, 0x3c, 0x60, 0xb2, 0xdb, 0xfd, 0xf6, 0xfb, 0xcf, 0xcf,
	0x52, 0xdb, 0x6d, 0xac, 0xa6, 0x9e, 0xf9, 0xcb, 0xc3, 0x10, 0x15, 0x3d, 0x2c, 0xae, 0x50, 0xf6,
	0xb6, 0x38, 0x8a, 0xfe, 0x77, 0xe3, 0x47, 0x6f, 0x18, 0x34, 0xe0, 0xc9, 0x05, 0x5e, 0xd2, 0x3c,
	0x51, 0xe4, 0x05, 0x79, 0x0e, 0x35, 0x67, 0x57, 0xeb, 0x8f, 0x15, 0x55, 0x79, 0x76, 0xde, 0x84,
	0x97, 0xb0, 0xdd, 0x47, 0x2a, 0x51, 0x92, 0xbd, 0x9d, 0x92, 0x53, 0xa3, 0xb9, 0x9a, 0x73, 0x79,
	0x2b, 0xd1, 0x2a, 0x85, 0x4f, 0x01, 0xee, 0x08, 0x5b, 0xe7, 0xdd, 0x98, 0xa9, 0x79, 0x1e, 0x7a,
	0x11, 0x5f, 0xf8, 0x57, 0x79, 0x88, 0x97, 0x09, 0xbf, 0xf6, 0x05, 0x13, 0x98, 0xb0, 0x14, 0x33,
	0x7f, 0x73, 0x35, 0x63, 0x3e, 0x8b, 0x12, 0x86, 0xa9, 0x0a, 0xb7, 0xf5, 0xc6, 0x75, 0xff, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xf8, 0x88, 0x62, 0x11, 0xfe, 0x02, 0x00, 0x00,
}
