apiVersion: apps/v1best2
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-visualizationserver
  name: ml-pipeline-visualizationserver
spec:
  selector:
    matchLabels:
      app: ml-pipeline-visualizationserver
  template:
    metadata:
      labels:
        app: ml-pipeline-visualizationserver
      spec:
        containers:
        - env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # TODO: Push image to GCR and obtain tag
          image: gcr.io/ml-pipeline/visualization-server:0.0.0
          imagePullPolicy: IfNotPresent
          name: ml-pipeline-visualizationserver
          ports:
          - containerPort: 8888
        serviceAccountName: ml-pipeline-visualizationserver